config/routes.rb
BlueskybreweryApp::Application.routes.draw do
  get "users/new"

  root :to => 'pages#home'

  match '/contact', :to => 'pages#contact'

  match '/about', :to => 'pages#about'

  match '/help', :to => 'pages#help'

  match '/calendar', :to => 'pages#calendar'

  match '/pages', :to => 'pages#home'

  match '/signup', :to => 'users#new'

 

  resources :beers
end

app/models/beer.rb
class Beer < ActiveRecord::Base
	belongs_to :style
	belongs_to :fermentabletype
	validates_presence_of :name
end

app/models/fermentabletype.rb
class Fermentabletype < ActiveRecord::Base
	has_many :beers
end

app/models/style.rb
class Style < ActiveRecord::Base
	#has_many :beers
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
	def index
		@title = "Beers"
		@beers = Beer.find(:all)
	end
	def show
		@beer = Beer.find(params[:id])
		@title = @beer.name 
	end
	def new
		@beer = Beer.new
		# @styles = Style.find(:all)
	end
	def create
		@beer = Beer.new(params[:beer])
		if @beer.save
			redirect_to :action => 'index'
		else
			flash[:error] = "Unable to create beer!"
			redirect_to beer_path(@beer)
		end
	end
	def edit
		@beer = Beer.find(params[:id])
		@styles = Style.find(:all)
	end
	def update
		@beer = Beer.find(params[:id])
		if @beer.update_attributes(params[:beer])
			redirect_to beer_path(@beer)
		else
			flash[:error] = "Unable to save beer!"
			redirect_to edit_beer_path(@beer)
		end
	end
	def delete
		Beer.find(params[:id]).destroy
		redirect_to :action => 'index'
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def about
  	@title = "About"
  end

  def calendar
  	@title = "Calendar"
  end

  def contact
  	@title = "Contact"
  end

  def help
    @title = "Help"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@title = "Sign Up"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Return a title on a per-page basis
	def title
		base_title = "Blue Skies Brewery"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/beer_helper.rb
module BeerHelper
	

def display_beer_style(beer)
	resp = "<h3>Style:</h3>"
	if beer.style==nil 
		resp += "Style Not Found"
	else
		resp += beer.style.name
	end
end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beers/edit.html.erb
<div>
<h1>Edit Beer Details</h1>
<%= form_for @beer do |f| %>
	<p>
		<h3><%= f.label :name %></h3>
		<%= f.text_field :name %>
	</p>
	<p>
		<h3><%= f.label :style %></h3>
		<% style_array = Style.all.map { |s| [s.name, s.id]} %>
		<%= f.select(:style_id, style_array) %>	
	</p>
	<p> <h3><%= f.label :fermentables %></h3>
		<%= f.text_area :fermentables %>
	</p>
	<p>
		<h3><%= f.label :hops %></h3>
		<%= f.text_area :hops %>
	</p>
	<p>
		<h3><%= f.label :recipe %></h3>
		<%= f.text_area :recipe %>
	</p>
		<h3><%= f.label :notes %></h3>
		<%= f.text_area :notes %>
	</p>
	<%= f.submit "Change" %>
<% end %>
<%= link_to 'Back', {:action => 'index'} %>
</div>

app/views/beers/index.html.erb
<% if @beers.blank? %>
<p> Get Brewing! There aren't any beers currently in the system!</p>
<% else %>
<div>
	<h2>Our Brews</h2>
	  <table>
	    <tr>
	      <th><h3>Beer</h3></th>
	      <th><h3>Style</h3></th>
	    </tr>

	  <% @beers.each do |beer| %>
	    <tr>
	      <td><%= link_to beer.name, beer %></td>
	      <td><%= beer.style.name %></td>
	    <tr>
	  <% end %>
	</table>


	<!-- <ul id="beers">
		<% @beers.each do |c| %>
		<li><%= link_to c.name, c %></li>
		<% end %>
	</ul> -->
	<% end %>
	<p><%= link_to "Add Another Beer", {:action => 'new'} %></p>
</div>

app/views/beers/new.html.erb
<h1>Brew A New Beer</h1>
<%= form_for @beer do |f| %>
  <div>
  	<p>
		<h3><%= f.label :name %></h3>
		<%= f.text_field :name %>
	</p>
	<p>
		<h3><%= f.label :style %></h3>
		<% style_array = Style.all.map { |s| [s.name, s.id]} %>
		<%= f.select(:style_id, style_array) %>	
	</p>
  </div>
  <div>
	<p> <h3><%= f.label :fermentables %></h3>
		<%= f.text_area :fermentables %>
	</p>
	<p>
		<h3><%= f.label :hops %></h3>
		<%= f.text_area :hops %>
	</p>
	<p>
		<h3><%= f.label :recipe %></h3>
		<%= f.text_area :recipe %>
	</p>
	<p> <h3><%= f.label :notes %></h3>
		<%= f.text_area :notes %>
	</p>
	<%= f.submit "Create" %>
  </div>
<% end %>
<%= link_to 'Back', {:action => 'index'} %>

app/views/beers/show.html.erb
<br/>
  <table>
  	<tr>
  	  <th width="150"><h1><%= @beer.name %></h1></th>
  	  <th></th>
  	</tr>

  	<tr>
  	  <td><h3>Brewed On:</h3></td>
  	  <td><%= @beer.created_at %></td>
  	</tr>

  	<tr>
  	  <td><h3>Style:</h3></td>
  	  <td><%= @beer.style.name %></td>
  	  <!--<%= raw(display_beer_style(@beer)) %>-->
  	</tr>

  	<tr>
  	  <td><h3>Malts and Grains: </h3></td>
	  <td><%= @beer.fermentables==nil ? "There are no Malts or Grains saved" : simple_format(@beer.fermentables) %></td>
	</tr>
	<tr> 
		<td><h3>Hops:</h3></td>
		<td><%= @beer.hops==nil ? "There aren't any hops saved" : simple_format(@beer.hops) %></td>
	</tr>
	<tr>
		<td><h3>Recipe:</h3></td>
		<td><%= @beer.recipe==nil ? "You haven't entered a recipe for this beer yet" : simple_format(@beer.recipe) %></td>
	</tr>
	<tr>
		<td><h3>Notes:</h3></td>
		<td><%= simple_format(@beer.notes) %></td>
	</tr>
  </table>
	<hr/>
	<%= link_to 'Back to List', {:action => 'index'} %> <br/>
	<%= link_to 'Edit', {:action => 'edit'} %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
  	<ul>
  		<li><%= link_to "About", :controller => :pages, :action => :about %></li>
  		<li><%= link_to "Contact", :controller => :pages, :action => :contact %></li>
  		<li><%= link_to "Home", :controller => :pages, :action => :home %></li>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to image_tag("BlueSkiesBrewery.png", :alt => "Blue Skies Brewery"), 
	  root_path
	%>
	<nav class="round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>
			<li><%= link_to "Sign In", '#' %></li>
		</ul>
	</nav>
</header> 

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<% stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!-- if lt IE 8> <%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

<%= stylesheet_link_tag :application %>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
  	<div>
        <% flash.each do |type, message| %>
	      <%= message %>
        <% end %>
        <section class="round">
    	  <%= yield %>
    	</section>
    	<%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About the Brewmasters</h1>
<p>
<table>
  <tr>
  	<th></th>
  	<th></th>
  	<th></th>
  </tr>
  <tr>
    <td><%= image_tag("jack.png", :alt => "Jack") %> </td>
    <td><%= image_tag("adam.png", :alt => "Adam") %> </td>
    <td><%= image_tag("dave.png", :alt => "Dave") %> </td>
  </tr>
  <tr>
  	<td><h3 align="center">Jack</h3></td>
  	<td><h3 align="center">Adam</h3></td>
  	<td><h3 align="center">David</h3></td>
  </tr>
</table>
</p>
<p>
	<h2>We love beer and we love to skydive. What more is there to say? </h2>
</p>

app/views/pages/calendar.html.erb
<h1>Funny Joke!</h1>
	<p>Seriously... I don't know enough to embed an awesome brew calendar yet. Soon... soon...</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
  <p>We currently brew in Madison, WI. Stop by to taste some of our delicious beer!</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
	Contact Jack Collins for website help.
</p>

app/views/pages/home.html.erb
<p class="round">
  <h1>Welcome to Blue Skies Brewery</h1>
  <h3>Beers brewed with fresh hops, delicious malts, and a taste of freefall</h3>
  	<ul>
  	  <li><%= link_to "Our Brews", 'beers#show' %></li>
  	  <li><%= link_to "About the Brewmasters", 'about' %></li>
  	  <li><%= link_to "Brewing Calendar", 'calendar' %></li>
  	</ul>

</p>

<%= link_to "Register", signup_path, :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Register</h1>
<p>We're working on registration. Stay tuned!</p>